services:
  hackforge:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_BASE_URL=https://enlarging-class-unmasking.ngrok-free.dev
    ports:
      - "3004:3000"
    environment:
      - NODE_ENV=production
    user: root
    restart: unless-stopped
    networks:
      - default
      - hackforge-network
    volumes:
      - /opt/hackforge/docker:/app/docker
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    driver: bridge
  hackforge-network:
    external: true
    name: hackforge-network
